// Change Form
export const CHANGE_FORM = 'CHANGE_FORM'
// Login
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
// Register
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
// Request Todos
export const REQUEST_TODOS = 'REQUEST_TODOS'
export const REQUEST_TODOS_FAILURE = 'REQUEST_TODOS_FAILURE'
export const REQUEST_TODOS_SUCCESS = 'REQUEST_TODOS_SUCCESS'
// Add Todos
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
// Delete Todos
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
// Toggle Completion
export const TOGGLE_COMPLETE_REQUEST = 'TOGGLE_COMPLETE_REQUEST'
export const TOGGLE_COMPLETE_FAILURE = 'TOGGLE_COMPLETE_FAILURE'
export const TOGGLE_COMPLETE_SUCCESS = 'TOGGLE_COMPLETE_SUCCESS'
//Visiblity Filters
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
};
